"""Register user use case."""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional, List
from app.domain.entities.user import User
from app.domain.value_objects.email import Email
from app.domain.value_objects.password import Password
from app.domain.exceptions.user_exceptions import UserAlreadyExistsException
from app.application.interfaces.repositories.user_repository import IUserRepository


@dataclass
class RegisterUserInput:
    """Input for register use case."""
    username: str
    email: str
    password: str
    full_name: Optional[str] = None
    role_ids: Optional[List[str]] = None


@dataclass
class RegisterUserOutput:
    """Output from register use case."""
    user: User


class RegisterUserUseCase:
    """
    Use Case: Register new user.
    
    Business Rules:
    1. Username must be unique
    2. Email must be unique and valid
    3. Password must meet strength requirements
    4. Hash password before storing
    5. Assign default role if none provided
    
    Single Responsibility: Handle user registration workflow
    """
    
    def __init__(
        self,
        user_repository: IUserRepository,
        password_hasher,  # Will be properly typed in infrastructure
    ):
        self.user_repo = user_repository
        self.password_hasher = password_hasher
    
    async def execute(self, input_data: RegisterUserInput) -> RegisterUserOutput:
        """
        Execute user registration.
        
        Args:
            input_data: Registration data
            
        Returns:
            RegisterUserOutput with created user
            
        Raises:
            UserAlreadyExistsException: Username or email already exists
            ValueError: Invalid email or weak password
        """
        # 1. Validate email using value object
        email = Email(input_data.email)
        
        # 2. Validate password strength using value object
        password = Password(input_data.password, require_special_char=False)
        
        # 3. Check if username already exists
        if await self.user_repo.exists_by_username(input_data.username):
            raise UserAlreadyExistsException(username=input_data.username)
        
        # 4. Check if email already exists
        if await self.user_repo.exists_by_email(input_data.email):
            raise UserAlreadyExistsException(email=input_data.email)
        
        # 5. Hash password
        hashed_password = self.password_hasher.hash(input_data.password)
        
        # 6. Create user entity
        user = User(
            id="",  # Will be generated by repository
            username=input_data.username,
            email=email.value,
            hashed_password=hashed_password,
            full_name=input_data.full_name,
            role_ids=input_data.role_ids or ["user"],  # Default role
            is_active=True,
            created_at=datetime.now(),
            updated_at=datetime.now(),
        )
        
        # 7. Persist user
        created_user = await self.user_repo.create(user)
        
        return RegisterUserOutput(user=created_user)
