"""Send message use case."""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional, List, Dict, Any
from domain.entities.chat_message import ChatMessage
from domain.entities.chat_session import ChatSession
from domain.enums.chat_message_role import ChatMessageRole
from domain.exceptions.chat_exceptions import ChatSessionNotFoundException
from application.interfaces.repositories.chat_repository import IChatRepository


@dataclass
class SendMessageInput:
    """Input for send message use case."""

    session_id: str
    role: ChatMessageRole
    content: str
    attachments: Optional[List[Dict[str, Any]]] = None
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class SendMessageOutput:
    """Output from send message use case."""

    message: ChatMessage
    session: ChatSession


class SendMessageUseCase:
    """
    Use Case: Send message in chat session.

    Business Rules:
    1. Session must exist
    2. Increment session message count
    3. Update session last_message_at
    4. Auto-generate title for first user message (optional)

    Single Responsibility: Send message and update session
    """

    def __init__(self, chat_repository: IChatRepository):
        self.chat_repo = chat_repository

    async def execute(self, input_data: SendMessageInput) -> SendMessageOutput:
        """
        Send message in session.

        Args:
            input_data: Message data

        Returns:
            SendMessageOutput with message and updated session

        Raises:
            ChatSessionNotFoundException: Session doesn't exist
        """
        # 1. Get session
        session = await self.chat_repo.get_session_by_id(input_data.session_id)
        if not session:
            raise ChatSessionNotFoundException(session_id=input_data.session_id)

        # 2. Create message entity
        message = ChatMessage(
            id="",  # Will be generated by repository
            session_id=input_data.session_id,
            role=input_data.role,
            content=input_data.content,
            attachments=input_data.attachments or [],
            metadata=input_data.metadata or {},
            created_at=datetime.now(),
        )

        # 3. Persist message
        created_message = await self.chat_repo.create_message(message)

        # 4. Update session (business logic in domain entity)
        session.add_message()

        # 5. Auto-generate title from first user message if needed
        if session.message_count == 1 and input_data.role == ChatMessageRole.USER:
            # Take first 50 chars as title
            auto_title = input_data.content[:50]
            if len(input_data.content) > 50:
                auto_title += "..."
            session.update_title(auto_title)

        # 6. Persist session updates
        updated_session = await self.chat_repo.update_session(session)

        return SendMessageOutput(
            message=created_message,
            session=updated_session,
        )
