"""Create chat session use case."""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional, List, Dict, Any
from app.domain.entities.chat_session import ChatSession
from app.application.interfaces.repositories.chat_repository import IChatRepository


@dataclass
class CreateSessionInput:
    """Input for create session use case."""

    user_id: str
    title: Optional[str] = "New Conversation"
    metadata: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None


@dataclass
class CreateSessionOutput:
    """Output from create session use case."""

    session: ChatSession


class CreateSessionUseCase:
    """
    Use Case: Create new chat session.

    Business Rules:
    1. Session must belong to a user
    2. Auto-generate title if not provided
    3. Initialize with empty message count

    Single Responsibility: Create chat session
    """

    def __init__(self, chat_repository: IChatRepository):
        self.chat_repo = chat_repository

    async def execute(self, input_data: CreateSessionInput) -> CreateSessionOutput:
        """
        Create new chat session.

        Args:
            input_data: Session creation data

        Returns:
            CreateSessionOutput with created session
        """
        # Create session entity
        session = ChatSession(
            id="",  # Will be generated by repository
            user_id=input_data.user_id,
            title=input_data.title or "New Conversation",
            metadata=input_data.metadata or {},
            tags=input_data.tags or [],
            message_count=0,
            created_at=datetime.now(),
            updated_at=datetime.now(),
        )

        # Persist session
        created_session = await self.chat_repo.create_session(session)

        return CreateSessionOutput(session=created_session)
